language: cpp

os:
    - linux
    - osx

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

dist: trusty

git:
    depth: 3

branches:
    only:
    - master

addons:
    apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['libsdl2-dev']

install:
    - mkdir build; cd build
    - cmake -DDOWNLOAD_SDL2_DEPENDENCY=ON -DCMAKE_INSTALL_PREFIX=~/AudioCodecs/ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..

script:
    - make -j 2
    - make install

