version: 1.4.{build}

environment:
  global:
    PLATFORMTOOLSET: "v140"
  matrix:
    - BUILD_TYPE: Debug
      COMPILER: MinGW
      COMPILER_FAMILY: MinGW
      GENERATOR: "MinGW Makefiles"
      PLATFORM: Win32
    - BUILD_TYPE: Release
      COMPILER: MinGW
      COMPILER_FAMILY: MinGW
      GENERATOR: "MinGW Makefiles"
      PLATFORM: Win32
    - BUILD_TYPE: Debug
      COMPILER: MinGW-w64
      COMPILER_FAMILY: MinGW
      GENERATOR: "MinGW Makefiles"
      PLATFORM: x64
    - BUILD_TYPE: Release
      COMPILER: MinGW-w64
      COMPILER_FAMILY: MinGW
      GENERATOR: "MinGW Makefiles"
      PLATFORM: x64
    - BUILD_TYPE: Debug
      COMPILER: MSVC15
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 14 2015 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: x64
      PLATFORMTOOLSET: "v140_xp"
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 14 2015 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: x64
      PLATFORMTOOLSET: "v140_xp"
    - BUILD_TYPE: Debug
      COMPILER: MSVC15
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v140_xp"
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v140_xp"
    - BUILD_TYPE: Debug
      COMPILER: MSVC17
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      PLATFORM: x64
      PLATFORMTOOLSET: "v141_xp"
    - BUILD_TYPE: Release
      COMPILER: MSVC17
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      PLATFORM: x64
      PLATFORMTOOLSET: "v141_xp"
    - BUILD_TYPE: Debug
      COMPILER: MSVC17
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v141_xp"
    - BUILD_TYPE: Release
      COMPILER: MSVC17
      COMPILER_FAMILY: MSVC
      GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v141_xp"

build_script:
  - md build-%COMPILER%-%BUILD_TYPE%-%PLATFORM%
  - cd build-%COMPILER%-%BUILD_TYPE%-%PLATFORM%
  - if [%COMPILER%]==[MinGW] set PATH=C:\MinGW\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - if [%COMPILER%]==[MinGW-w32] set PATH=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - if [%COMPILER%]==[MinGW-w64] set PATH=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCMAKE_PREFIX_PATH=. -DCMAKE_INSTALL_PREFIX=libOPNMIDI -DlibOPNMIDI_STATIC=ON -DlibOPNMIDI_SHARED=ON ..
  - if [%COMPILER_FAMILY%]==[MinGW] cmake --build . --config %BUILD_TYPE% -- -j 2
  - if [%COMPILER_FAMILY%]==[MinGW] mingw32-make install
  - if [%COMPILER_FAMILY%]==[MSVC] cmake --build . --config %BUILD_TYPE% --target install
  - 7z a -t7z -mx9 "libOPNMIDI-%COMPILER%-%BUILD_TYPE%-%PLATFORM%.7z" "libOPNMIDI"
  - move libOPNMIDI-%COMPILER%-%BUILD_TYPE%-%PLATFORM%.7z ..

artifacts:
  - path: 'libOPNMIDI-$(COMPILER)-$(BUILD_TYPE)-$(PLATFORM).7z'

deploy:
  - provider: Environment
    name: WohlnetFTP

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

